### ISSUE TITLE
Headers no longer available in 1.10.0

### ISSUE THREAD

**Issue by markusahlstrand** [Azure/azure-documentdb-node#146]
I just upgraded from 1.8.0 to 1.10.0 and the headers are no longer returned in this query:
`client.queryDocuments(collectionLink, querySpec, options).toArray((err, items, headers) => {`

I had a look in the code and don't understand the logic completely, but it seems to recursively iterate over the results and overwrite the headers in the second recursion:
https://github.com/Azure/azure-documentdb-node/blob/master/source/lib/queryIterator.js#L144

Added a quick patch to validate that headers are defined which solved the issue, but I don't think this is the ideal solution. Is there a reason to recurse over the results? Is it that the iteration may trigger additional server requests?

**Comment by rnagpal** [comment]
@moderakh Can you please look into this?

**Comment by moderakh** [comment]
@markusahlstrand  queryIterator.toArray(callback) collects all the results and passes the array of collected results to the callback.

The total results size could be more than the page-fetch-size, and so queryIterator has to do multiple fetches to retrieve all results. 

I wonder what's your use case here, why do you need to know the response-headers?

**Comment by markusahlstrand** [comment]
Hi @moderakh,

We use the response headers to track the request charge and resource usage, both to ensure that we provision sufficient capacity and to understand which queries could be optimised.

I had another look at the code and it seems that an empty resource is passed back to signal that there are no more results. The headers are overwritten at line 144 and the check for end of results are at 146, so by swapping these two lines the simplest case would be solved? 

The question is how to handle the headers when the proxyExecutionRequest makes additional server requests. From a sdk user perspective I would prefer if it returned an array of headers, so that it's clear exactly what happened.

**Comment by moderakh** [comment]
Hello @markusahlstrand

By swapping those lines you should get the last response header; however that won't help you much because if there are multiple requests (page-fetch-size < total result size) you will only get the request-charge corresponding to the last query.

Returning a response header wasn't documented feature. We planning to do the following fix:
toArray() internally tracks and sums up the request-charge and item-count (if there are multiple requests) and overwrites the request-charge and item-count in the last response header with the corresponding summed up value, then return the last response header with the overwritten values.

**Comment by markusahlstrand** [comment]
Hi @moderakh,

This sounds like a good solution.

Thanks

**Comment by saibotsivad** [comment]
@moderakh What's the status on this?

I inherited some old code which was using the response headers property for a similar purpose: to track the request charge/resource use.

It sounds like you are saying I should still be able to get the `request-charge` (formerly `x-ms-request-charge` in the `headers` object) but I cannot see a way to do that in `1.10.0`.

**Comment by moderakh** [comment]
@saibotsivad as mentioned above this is a non-documented feature which is broken.

We will fix this in upcoming releases.

**Comment by saibotsivad** [comment]
Just to be clear, if we need to use this (undocumented/unsupported) feature, it sounds like we should pin the version we use to whatever the latest version before 1.10 is (e.g. 1.9.x)? That's a workable solution for us, we'll just wait until the feature is readded. Thanks!

**Comment by moderakh** [comment]
Thanks @saibotsivad we will fix this.

**Comment by markusahlstrand** [comment]
Hi @moderakh ,

It looks like this wasn't part of the 0.10.1 release? Do you know when this is expected to be implemented? If work hasn't already started on this feature we could see if we can make a PR to get it in?

**Comment by rnagpal** [comment]
@markusahlstrand Feel free to submit a PR and we can review and merge it.

**Comment by moderakh** [comment]
Please use queryIterator.executeNext(callback(err, resources, headers)).
headers should have the request charge for both single partition collection and multi partition collection. Please use the latest version.

**Comment by saibotsivad** [comment]
@moderakh Previously this issue was marked as closed because it was a ["non-documented feature"](https://github.com/Azure/azure-documentdb-node/issues/146#issuecomment-252721638). I still don't see the headers as being a [documented returned property](http://azure.github.io/azure-documentdb-node/QueryIterator.html), so even if it works _now_ with the latest version of [documentdb](https://www.npmjs.com/package/documentdb) it doesn't sound like there is any guarantee that it will work in the future.

Do you know if there is an intent to document the headers in the `queryIterator.executeNext` method at some point? I imagine that might take a while?

**Comment by moderakh** [comment]
@saibotsivad we will support returning request charge if you use `queryIterator.executeNext(callback(err, resources, headers))`
In case of a cross partition query `headers` will at least have the request charge.

Feel free to send a PR for updating the documentation for executeNext(.) saying that headers will accessible as the third arg.
