### ISSUE TITLE
Unit tests take fairly long time to run

### ISSUE THREAD

**Issue by markusahlstrand** [Azure/azure-documentdb-node#165]
When running the unit tests after doing changes to the sdk locally it took roughly 2 hours to run the unit tests. I could images two ways that this time could be decreased:
- Separate the integration tests that hit's against an actual database from the unit tests.
- Move the deletion and creation of the database out of the permissionCRUDOverMultiplePartitionsTest function. Maybe there could be one test that verifies that the database/collections are successfully created and the other tests can use a database created in the before hook?

What are your thoughts?

**Comment by rnagpal** [comment]
@markusahlstrand Thanks for you feedback. I believe we have separate tests for end-to-end scenarios and unit tests but probably they need to be moved in appropriate sub folder to have that distinction and can be run independently. Regarding second point, we have been thinking of doing that but haven't got chance yet and this is the right way since most of the time the tests take is creating/deleting collections for every test case which results in lot of time and also rate limiting errors on which we retry automatically. 

If you are willing to refactor the tests, we would happy to do the review of your PR and would appreciate your contribution!

**Comment by markusahlstrand** [comment]
Hi @rnagpal,

Thanks for the quick reply. If this is in line with your thoughts I'll see if I can do a small refactor and send a PR.

**Comment by christopheranderson** [comment]
Stale (but some of these issues are addressed in the v2 SDK which has tests properly separated.
