### ISSUE TITLE
DEPTH_ZERO_SELF_SIGNED_CERT error with emulator

### ISSUE THREAD

**Issue by graham-sportsmgmt** [Azure/azure-documentdb-node#249]
node.js version 8.11.1
documentdb sdk version 1.14.5
Windows 10 X64 17713_rs5

I set up the documentdb emulator per [the instructions here](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator).

Every request to documentdb produced this error:

```
{   "code": "DEPTH_ZERO_SELF_SIGNED_CERT" }
```

I was able to solve this using the information provided in [this issue](https://github.com/Azure/azure-documentdb-node/issues/157) and the following code:

```
const { DocumentClient, DocumentBase } = require('documentdb');
const connectionPolicy = new DocumentBase.ConnectionPolicy();
connectionPolicy.DisableSSLVerification = true;
const client = new DocumentClient(config.host, { "masterKey": config.key }, connectionPolicy);
```

1. This code is no longer optimal for deployment into a production environment, we'll have to add conditional logic now to detect the environment it's deployed into and act accordingly.  My preference would be to use a configuration parameter for this instead so we can keep the code constant between environments (we use config with .json files but others use environment variables).

2. [This issue](https://github.com/Azure/azure-documentdb-node/issues/153) has a comment stating that this problem was addressed in 1.10.1

3. The official emulator documentation should probably address this in the troubleshooting section.

**Comment by christopheranderson** [comment]
1. I think this is really up to how you manage your config, but there are a few ways to manage this. We can't generalize enough to put this in the SDK, but it's fairly common to have some code like:

```js
if(endpoint.contains("localhost:8081") {
   connectionpolicy.DisableSSLVerification = true;
   console.log("WARNING: Disabling SSL Verficiation because we detected the emulator was being used");
}
```

If you don't feel comfortable with that auto-discovery from localhost, then have an environment variable with config option like:

```js
connectionpolicy.DisableSSLVerification = process.env.COSMOS_DISABLE_SSL_VERIFICATION === "true"
```

I'd advocate a lot of your config should be able to be set via environment variables so you can tune your code without having to redeploy, in the future. (Timeouts/retries/etc.)

You can also get around all of this by trusting the cert from the emulator by following these steps: https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#export-the-ssl-certificate

2. The issue was "solved" in 2 by adding the option you used, so not sure what you're asking on this one.

3. I've forwarded this issue to our content writer and PM for them to think about how to improve the experience. This is alluded to in the SSL cert section of the doc (linked above), but it could probably be in the troubleshooting section as well, agreed. If you want, you can actually open that issue directly on the doc page (unfortunately, it won't be tracked here).

Closing this since I think I've addressed your points.

**Comment by RobbieLD** [comment]
Anyone looking for the updated solution to this it's [here](https://github.com/MicrosoftDocs/azure-docs/issues/57861)
